version: 0.0.0_1
clone_depth: 3

branches:
    only:
     - master

image: Visual Studio 2015
os: Visual Studio 2015

before_build:
 - ps: New-Item -ItemType Directory -Path ./build/msvc_14
 - ps: Set-Location ./build/msvc_14
 - cmd: cmake -G"Visual Studio 14 2015" ../..

build:
    project: C:\projects\free3ds\build\msvc_14\free3ds.sln
test: off
