version: 0.0.0_{build}
clone_depth: 3

branches:
  only:
    - master

image: Visual Studio 2015
os: Visual Studio 2015

environment:
  matrix:
    - Generator: "MSYS2 Makefiles"
    - Generator: "Visual Studio 14 2015"

before_build:
  - $bash = 'C:\msys64\usr\bin\bash.exe'
  - ps: New-Item -ItemType Directory  -ErrorAction SilentlyContinue -Path ./build/$env:Generator
  - ps: Set-Location ./build/$env:Generator
  - ps: cmake -G$env:Generator ../..
  - IF %Generator% == "MSYS2 Makefiles" bash@(pacman --noconfirm -Syu pacman)
  - IF %Generator% == "MSYS2 Makefiles" bash@(pacman --noconfirm -S mingw-w64-x86_64-toolchain)
  - IF %Generator% == "MSYS2 Makefiles" bash@(pacman --noconfirm -S libtool make)
  - cmake $env:Generator ../..

build:
  - IF %Generator% == "Visual Studio 14 2015" cmake --build . --target ALL_BUILD
  - IF %Generator% == "MSYS2 Makefiles" C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/free3ds/build/MSYS2; /mingw64/bin/cmake --build . --target all"
  - $LASTEXITCODE

test: off
