version: 0.0.0_1.{build}
clone_depth: 3

branches:
    only:
     - master

image: Visual Studio 2015
os: Visual Studio 2015

environment:
  matrix:
    - generator: "Unix Makefiles"
    - generator: "Visual Studio 14 2015"

before_build:
 - ps: |
       if($env:generator == "Visual Studio 15")
       {
           New-Item -ItemType Directory -Path ./build/msvc_14
           Set-Location ./build/msvc_14
           cmake -G"Visual Studio 14 2015" ../..
       }
       else
       {
           C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu pacman"
           C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
           C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S libtool make"
           C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-cmake"
           New-Item -ItemType Directory -Path .\build\MSYS2
           C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/free3ds/build/MSYS2; /mingw64/bin/cmake -G'Unix Makefiles' ."
       }

build:
 - ps: |
       if($env:generator == "Visual Studio 15")
       {
           cmake --build . --target all
       }
       else
       {
           C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/free3ds/build/MSYS2; /mingw64/bin/cmake --build . --target all"
       }

test: off
